### ISSUE TITLE
dune-release publish distrib use the wrong uri

### ISSUE THREAD

**Issue by Julow** [tarides/dune-release#172]
`dune-release publish distrib` tries to push the git tag to a made up uri:

```
[?] Push tag 0.12 to git@github.com:ocaml-ppx/ocamlformat.git? [Y/n]
```

That uri won't match any key in my config and the push will fail.

Answering `n` will abort the whole procedure, so I can't push manually and skip this step.

**Comment by Julow** [comment]
For more context: with my configuration, the corrent uri would be `gh:ocaml-ppx/ocamlformat`. It cannot be guessed because it's not in my git remotes.

I can think of 2 fixes:
- Check if the tag is already pushed and don't ask me to push it again
  If `git push` fail, it asks me to push it manually
- Ask me which url I want to use between that uri, my git remotes and the https uri

**Comment by NathanReb** [comment]
A quick fix for that would be to offer you to skip that step so that you can push the tag yourself and leave the rest to `dune-release`.

A next step could be to allow local release configurations so that you can tell `dune-release` where to push and overwrite the default behaviour.

**Comment by Julow** [comment]
> A quick fix for that would be to offer you to skip that step so that you can push the tag yourself and leave the rest to `dune-release`.

Looks good to me :)

**Comment by sporto** [comment]
For me dune-release wants to push the tags to `git://`

```
Push tag 0.3.0-7-g6ea32f3 to git://github.com/sporto/jwto? [Y/n]
```

This fails with ` You can't push to git://github.com/sporto/jwto.git`

But my remote is `url = git@github.com:sporto/jwto.git`

**Comment by NathanReb** [comment]
Hmm that one's weird. Thanks for reporting it, we'll look into it!

**Comment by Julow** [comment]
I think this issue is obsolete. Dune-release still has issues with my URLs, though: https://github.com/tarides/dune-release/issues/479
