### ISSUE TITLE
Remove the bistro command

### ISSUE THREAD

**Issue by gpetiot** [tarides/dune-release#241]
Calling `dune-release` without a sub-command is the same as calling `dune-release bistro`. Is there really a benefit to having this command? (not sure this is even properly documented)

**Comment by NathanReb** [comment]
Maybe a better suited name would do the trick, something like `dune-release auto` or `dune-release all`.

Adding documentation and stating that it's the default command seems good enough but I think it's already the case for bistro

We can't remove it without doing a major release but if we wish to improve the doc and eventually add an alias we can do that already! We could then deprecate it and finally drop it when releasing 2.0!

**Comment by Leonidas-from-XIV** [comment]
@NathanReb Should we move this for the 2.0.0 milestone? I fear that given we already started, it is a bit late to remove but we could at least deprecate it.

**Comment by NathanReb** [comment]
I think it's fine to remove it in 2.0 without warning. Not best practice but I doubt anybody has a script that runs `dune-release bistro` so it's unlikely to break anything serious, and I doubt anyone would bother typing `dune-release bistro` when it's the same as `dune-release`.
