### ISSUE TITLE
dune-release fails with curl: command not found

### ISSUE THREAD

**Issue by bikallem** [tarides/dune-release#456]
`dune-release` fails with the following command:
```
[-] Creating release 4.3.0 on https://github.com/lemaetech/http-cookie.git via github's API
dune-release: [ERROR] curl execution failed: Non 0 exit code Exit code 127
  {status=Exit code 127; stderr="/bin/sh: line 1: curl: command not found
  ";
  stdout=""}
```

Curl is in the path
```
$ /bin/sh
sh-5.1$ curl --version
curl 7.86.0 (x86_64-pc-linux-gnu) libcurl/7.86.0 OpenSSL/3.0.7 zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libssh2/1.10.0
 nghttp2/1.49.0
Release-Date: 2022-10-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tft
p 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL thre
adsafe TLS-SRP UnixSockets zstd
```

**Comment by Leonidas-from-XIV** [comment]
Thanks for the report. Can you run `which curl` (or similar) from the shell where you're running `dune-release`? `dune-release` uses `curly` for making HTTP requests, so it needs a curl binary in the `$PATH`.

**Comment by bikallem** [comment]
> uses curly for making HTTP requests, so it needs a curl binary in the $PATH.

Do you mean `curl`? If so, here is the output:

```
$ /bin/sh
sh-5.1$ which curl
/run/current-system/sw/bin/curl
```

**Comment by Leonidas-from-XIV** [comment]
Is `/run/current-system/sw/bin` in your `$PATH`? We use the [curly](https://opam.ocaml.org/packages/curly/) package which is an OCaml wrapper around `curl`, but as much as I look into its source, it doesn't use any hardcoded paths for curl (like `/usr/bin/curl` or so), it just uses the regular `PATH` lookup.

**Comment by bikallem** [comment]
It seems `curly` doesn't set the PATH env when spawning `curl`. Here is the PR to fix it https://github.com/rgrinberg/curly/issues/11. After the fix is merged and released `dune-release` probably needs a version bump on dependencies list. Will keep this open till then. Thanks for your help.

**Comment by Leonidas-from-XIV** [comment]
Thanks for your investigation! I will bump the minimal required version once a new version of curly is out.

**Comment by yawaramin** [comment]
Looks like this can be bumped up to curly 0.3.0 now?
