### ISSUE TITLE
No GitHub token error message: copy -> paste

### ISSUE THREAD

**Issue by maxRN** [tarides/dune-release#491]
When not GitHub token is configured, the following error message is displayed:

```shell
[!] /Users/maxrn/.config/dune/github.token: file does not exist
[-] Dune-release needs a Github Personal Access Token to proceed with API requests.
[-] To create a new token, please visit:
    https://github.com/settings/tokens/new
[-] and create a token with the public_repo scope only.
[?] Please copy the token here:
```

I think the last sentence should be `Please paste the token here:`. Since what the user is really doing here is to paste it and not copy it.

**Comment by Leonidas-from-XIV** [comment]
From a grammar perspective both are fine here (since you can "copy something to a place"), but "paste" is probably the more common usage. If you want you can submit a PR!

**Comment by maxRN** [comment]
I've never heard of copy being used in that way, TIL! Thanks for being so open even though it's such a minor thing.

**Comment by Leonidas-from-XIV** [comment]
Take for example

```sh
$ cp README.md LICENSE.md
```

You'd say you copied the file to `LICENSE.md` and saying you pasted the file would sound really weird. But your point is true that for text one rather uses "paste" as that's the more appropriate term.
